spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.0.169:3306/edentist?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  rabbitmq:
    host: localhost
    port: 5672

edentist:
  mq:
    exchange: edentist.exchange
    routingkey: edentist.routingkey
    username: guest
    password: guest
    queue-name: edentist.queue
    mailSender: edentist18@gmail.com
  app:
    secret: edentistmegasecretapplicaitonkey123456789
    superadminEmail: edentist18@gmail.com
    newsapiclient:
      token: 7c18617c8c3d4d32bae73e8970677dd8
      limit: 15
      timeout: 1500