spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/edentist?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  rabbitmq:
    host: localhost
    port: 5672

edentist:
  mq:
    exchange: edentist.exchange
    routingkey: edentist.routingkey
    username: guest
    password: guest
    queue-name: edentist.queue
    mailSender: edentist18@gmail.com
  app:
    secret: edentistmegasecretapplicaitonkey123456789
    superadminEmail: edentist18@gmail.com
    newsapiclient:
      token: 5b825622a50744249be6b8b3197a8337
      limit: 15
      timeout: 1500