version: '3.3'
services:
  db:
    container_name: 'db'
    build: mysql
    image: 'database'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'edentist'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

  mq:
    container_name: 'mq'
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'

#  product-server:
#    container_name: 'product-server'
#    build: ../../product-server/src/main/resources
#    image: kdduni98/product-server
#    depends_on:
#      - db
#      - mq
#    restart: on-failure
#    ports:
#      - 8080:8080

  message-server:
    container_name: 'message-server'
    build: ../../message-server/src/main/resources
    image: kdduni98/message-server
    depends_on:
      - mq
    restart: on-failure
    ports:
      - 9002:9002
