spring:
    datasource:
        url: jdbc:mysql://localhost:3306/edentist?createDatabaseIfNotExist=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: pass

    jpa:
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl.auto: update
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    rabbitmq:
        host: localhost
        port: 5672

    mail:
        host: smtp.gmail.com
        port: 587
        username: edentist18@gmail.com
        password: fmetudivmccsnihz
        properties:
            mail.smtp:
                auth: true
                starttls.enable: true

edentist:
    mq:
        exchange: edentist.exchange
        routingkey: edentist.routingkey
        username: guest
        password: guest
        queue-name: edentist.queue
