
spring:
    main:
         allow-bean-definition-overriding: true

    rabbitmq:
        host: localhost
        port: 5672

    mail:
        host: smtp.gmail.com
        port: 587
        username: edentist18@gmail.com
        password: fmetudivmccsnihz
        properties:
            mail.smtp:
                auth: true
                starttls.enable: true
messageQueue:
    mq:
#        exchange: edentist.exchange
#        routingkey: edentist.routingkey
        username: guest
        password: guest
        queue-name: edentist.queue
server:
    port: 8081
